create_clock -name core_clk -period 8.0 [get_ports clk_i]
set_clock_uncertainty 1.0 [get_clocks core_clk]
set_input_delay  0 -clock core_clk [all_inputs]
set_output_delay 0 -clock core_clk [all_outputs]
set_input_delay 4 -clock core_clk [get_port reset_i]
